"""Save applicants in PostgreSQL and avoid inserting the same URL twice.

Run from module_4 with: python -m src.load_data
"""
import math
import re
from pathlib import Path

from .clean import _date, load_data
from .database import connect
from .paths import PROJECT_FOLDER

FOLDER = PROJECT_FOLDER

CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS applicants (
    p_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program TEXT,
    comments TEXT,
    date_added DATE,
    url TEXT NOT NULL UNIQUE,
    status TEXT,
    term TEXT,
    us_or_international TEXT,
    gpa DOUBLE PRECISION,
    gre DOUBLE PRECISION,
    gre_v DOUBLE PRECISION,
    gre_aw DOUBLE PRECISION,
    degree TEXT,
    llm_generated_program TEXT,
    llm_generated_university TEXT
);
"""

# %s is a placeholder. psycopg passes the values separately and safely.
# ON CONFLICT tells PostgreSQL to ignore a URL already in the table.
INSERT_APPLICANT = """
INSERT INTO applicants (
    program, comments, date_added, url, status, term,
    us_or_international, gpa, gre, gre_v, gre_aw, degree,
    llm_generated_program, llm_generated_university
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON CONFLICT (url) DO NOTHING;
"""


def text_or_none(value):
    """Blank text becomes SQL NULL (a missing value)."""
    if value is None:
        return None
    text = str(value).strip()
    if text == "":
        return None
    return text


def number_or_none(value):
    """A missing or invalid score should not prevent loading the applicant."""
    try:
        number = float(value)
        if math.isfinite(number):
            return number
        return None
    except (TypeError, ValueError):
        return None


def applicant_values(row):
    """Put JSON fields into the same order as INSERT_APPLICANT above."""
    status = text_or_none(row.get("status"))
    decision = re.match(r"(Accepted|Rejected|Wait\s*listed|Interview)", status or "", re.I)
    if decision:
        status = decision.group(1).title().replace("Waitlisted", "Wait listed")

    return (
        row.get("program"),  # Keep the original university/program spelling.
        text_or_none(row.get("comments")),
        _date(row.get("date_added_iso") or row.get("date_added")),
        text_or_none(row.get("url")),
        status,
        text_or_none(row.get("term")),
        text_or_none(row.get("US/International")),
        number_or_none(row.get("GPA")),
        number_or_none(row.get("GRE")),
        number_or_none(row.get("GRE V")),
        number_or_none(row.get("GRE AW")),
        text_or_none(row.get("Degree")),
        text_or_none(row.get("llm-generated-program")),
        text_or_none(row.get("llm-generated-university")),
    )


def insert_applicants(rows, database_url=None):
    """Insert one batch in a transaction: either the whole batch works or none does."""
    values = []
    skipped = 0
    for row in rows:
        if not text_or_none(row.get("url")):
            skipped += 1
            continue
        values.append(applicant_values(row))

    with connect(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(CREATE_TABLE)
            inserted = 0
            if values:
                cursor.executemany(INSERT_APPLICANT, values)
                inserted = cursor.rowcount
    return inserted, skipped


def read_applicants(folder=FOLDER):
    """Use cleaned data as the base; join the two LLM names by URL."""
    cleaned = load_data(Path(folder) / "applicant_data.json")
    extended = load_data(Path(folder) / "llm_extend_applicant_data.json")
    names_by_url = {}
    for applicant in extended:
        names_by_url[applicant["url"]] = applicant

    applicants = []
    for row in cleaned:
        applicant = row.copy()
        names = names_by_url.get(row.get("url"), {})
        applicant["llm-generated-program"] = names.get("llm-generated-program")
        applicant["llm-generated-university"] = names.get("llm-generated-university")
        applicants.append(applicant)
    return applicants


def applicant_records(database_url=None):
    """Read stored rows as dictionaries with every Module 3 field."""
    from psycopg.rows import dict_row
    with connect(database_url) as connection:
        with connection.cursor(row_factory=dict_row) as cursor:
            cursor.execute("SELECT * FROM applicants ORDER BY p_id")
            return cursor.fetchall()


if __name__ == "__main__":
    applicants = read_applicants()
    inserted_count, skipped_count = insert_applicants(applicants)
    duplicate_count = len(applicants) - inserted_count - skipped_count
    print(f"Read {len(applicants)} cleaned entries.")
    print(f"Inserted {inserted_count} new entries; skipped {skipped_count} without a URL.")
    print(f"Already present: {duplicate_count}.")
